# ML
Implementação do algoritmo de regressão linear


Predição de preços de casas levando em consideração o tamanho e quantidade de quartos.

In [19]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [77]:
data = pd.read_csv("data.csv", names = ['Tamanho','Quartos','Preços'])
print(data.head())


   Tamanho  Quartos  Preços
0     2104        3  399900
1     1600        3  329900
2     2400        3  369000
3     1416        2  232000
4     3000        4  539900


In [78]:
X=data.iloc[:, 0:2].values
y = data.iloc[:, 2:3].values
print(X.shape)
y.shape

(47, 2)


(47, 1)

In [70]:
def feature_scaling(X):
    X_norm = X
    mu = np.zeros([1, X.shape[1]])
    sigma = np.zeros([1, X.shape[1]])
    
    print(mu.shape)
    print(sigma.shape)
    print(X_norm.shape)
   
    mu = np.mean(X, axis=0)
    X_norm = X_norm - mu
    sigma = np.std(X, axis = 0)
    
    X_norm = np.divide(X_norm,sigma)
    #x_norm = np.divide((X - mu),sigma)
    
    
    return X_norm,mu,sigma

In [79]:
X,mu,sigma = feature_scaling(X)
print(X)

(1, 2)
(1, 2)
(47, 2)
[[  1.31415422e-01  -2.26093368e-01]
 [ -5.09640698e-01  -2.26093368e-01]
 [  5.07908699e-01  -2.26093368e-01]
 [ -7.43677059e-01  -1.55439190e+00]
 [  1.27107075e+00   1.10220517e+00]
 [ -1.99450507e-02   1.10220517e+00]
 [ -5.93588523e-01  -2.26093368e-01]
 [ -7.29685755e-01  -2.26093368e-01]
 [ -7.89466782e-01  -2.26093368e-01]
 [ -6.44465993e-01  -2.26093368e-01]
 [ -7.71822042e-02   1.10220517e+00]
 [ -8.65999486e-04  -2.26093368e-01]
 [ -1.40779041e-01  -2.26093368e-01]
 [  3.15099326e+00   2.43050370e+00]
 [ -9.31923697e-01  -2.26093368e-01]
 [  3.80715024e-01   1.10220517e+00]
 [ -8.65782986e-01  -1.55439190e+00]
 [ -9.72625673e-01  -2.26093368e-01]
 [  7.73743478e-01   1.10220517e+00]
 [  1.31050078e+00   1.10220517e+00]
 [ -2.97227261e-01  -2.26093368e-01]
 [ -1.43322915e-01  -1.55439190e+00]
 [ -5.04552951e-01  -2.26093368e-01]
 [ -4.91995958e-02   1.10220517e+00]
 [  2.40309445e+00  -2.26093368e-01]
 [ -1.14560907e+00  -2.26093368e-01]
 [ -6.90255715e-

In [90]:
#Transforma em arrays matematicos
X = np.array(X)
y = np.array(y).flatten()

#pega valores de quantidade de exemplos e caracteristicas
m,d = X.shape

#instancia hyperparametros
#instandia theta com dimensão d+1 por causa de theta 0
theta = np.zeros(d+1)
iterations = 100
alpha = 1


print(theta.shape)
print(y.shape)
print(X.shape)

(3,)
(47,)
(47, 2)


In [91]:
#insere coluna de 1 como variavel nula na multiplicação e para generalizar algoritmo para N features
X = np.insert(X,0,1,axis=1)

In [92]:
def cost_function(X, y, theta):
#Funcao de custo, quanto menor o custo, melhor fit    
    m = len(y) 
    
    J = np.sum((X.dot(theta)-y)**2)/(2*m)
    
    return J

In [93]:
#verifica função de custo
print(cost_function(X,y,theta))

65591548106.5


In [95]:
def gradient_descent(X,y,theta, alpha, num_inters):
#Funcao gradiente descendente, atualiza os thetas encontrando o minimo local    
    j_cost = list()
    print(m)
    for i in range(num_inters):
     
        gradient = X.T.dot(((X.dot(theta))-y))/m
        theta = theta - (alpha*gradient)
        cost = cost_function(X, y, theta)
        j_cost.append(cost)
        
       
    
    return theta, j_cost

In [96]:
#Encontra os thetas para predict
(t),(j) = gradient_descent(X,y,theta,alpha, iterations)

47


In [97]:
print("compute of the theta:")
print(t.shape)
t

compute of the theta:
(3,)


array([ 340412.65957447,  109447.79646964,   -6578.35485416])

In [104]:
house = np.array([1650,3])
house = house-mu
house = np.divide(house,sigma)

In [105]:
house = np.insert(house, 0,1, axis = 0)


In [106]:
print(house,house.shape)


[ 1.         -0.44604386 -0.22609337] (3,)


In [107]:
price = np.dot(house.T,t)

In [108]:
print(price)

293081.464335


In [109]:
def eqnormal(X,y):
    theta = np.zeros([X.shape[1],1])
    
    pinv = np.linalg.pinv(np.dot(X.T, X))
    theta = np.dot(np.dot(pinv, X.T), y)
    
    return theta

In [110]:
X = np.array(data[['Tamanho','Quartos']])



m,d = X.shape

y = np.array(data['Preços'])


theta = np.array([0,0,0])

iterations = 50
alpha = 0.1

#X = feature_scaling(X)

X = np.insert(X,0,1,axis=1)

In [111]:
theta = eqnormal(X,y)

In [112]:
price = np.dot(np.array([1,1650,3]),theta)

In [113]:
price

293081.4643349892